### ISSUE TITLE
Examples does not build with winit v0.8

### ISSUE THREAD

**Issue by gbip** [vulkano-rs/vulkano-examples#13]
Hello,
I tried to reproduce the basic triangle example on my side, and it does not seem to build when using winit v0.8.3.
The error is about vulkano_win::VkSurfaceBuilder :
```
error[E0599]: no method named `build_vk_surface` found for type `winit::WindowBuilder` in the current scope
  --> src/main.rs:37:37
   |
37 |         winit::WindowBuilder::new().build_vk_surface(&event_loop, instance.clone()).unwrap();
   |                                     ^^^^^^^^^^^^^^^^

```

Cargo.toml :
```toml
[dependencies]
winit="0.8.3"
vulkano="0.7.2"
vulkano-shader-derive="0.7.2"
vulkano-win="0.7.2"
```
Thanks,

**Comment by tomaka** [comment]
Unfortunately you have to use winit 0.7 with vukano-win 0.7. Using any other version of winit will lead to the error you're seeing.
